server:
port: 8080
#?????? ?? ???? 8080

spring:
datasource:
url: jdbc:mysql://localhost:3306/boardStudy?serverTimezone=UTC
username: "root"
password: "tmdqja9569!"
driver-class-name: com.mysql.cj.jdbc.Driver
jpa:
hibernate:
# create, update
ddl-auto: update
naming:
physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
use-new-id-generator-mappings: false
database: mysql
database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
properties:
hibernate:
show_sql: true
format_sql: true
mvc:
pathmatch:
matching-strategy: ant_path_matcher # about swagger


